# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/updating/#never-change-the-answers-file-manually
_commit: v0.0.9-34-gc32b215
_src_path: gh:FallingColors/hexdummy
advanced: true
capitalize_platforms: true
classname: HexActionManifest
default_branch: main
description: Hex Action Manifest addon for Hex Casting
display_name: Hex Action Manifest
github_repo: Hex-Action-Manifest
github_user: Master-Bw3
homepage_url: https://master-bw3.github.io/Hex-Action-Manifest
java_version: 17
kotlin: true
mappings_name: Yarn
minecraft_version: 1.20.1
mod_version: 1.0.0
modid: hex_action_manifest
package: mod.master_bw3.hex_action_manifest
sources_url: https://github.com/Master-Bw3/Hex-Action-Manifest
