name: Generate Manifest

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
  # add more branches here to enable deploying the web book to Pages from those branches
  # eg. '["main", "1.19"]'
  MAIN_BRANCHES: '["main"]'

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - uses: gradle/actions/setup-gradle@v3

      - name: Build mod
        run: chmod +x ./gradlew && ./gradlew :Fabric:build

      - name: Run DataGen
        run: timeout 2m ./gradlew :Fabric:runDataGen || exit 0 #janky fix for datagen not ending for some reason

      - name: Upload manifest
        uses: actions/upload-artifact@v3
        with:
          name: manifest
          path: Fabric/src/generated/data/data/hex_action_manifest/hex_actions/manifest.json

  release-project:
    name: Create Release
    runs-on: ubuntu-latest
    needs: generate-manifest

    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: manifest

      - name: Test artifact download
        run: ls /home/runner/work/Hex-Action-Manifest/Hex-Action-Manifest

      - name: get date
        id: step_one
        run: echo "date=$(date +%F)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: ${{ env.date }} run ${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: /home/runner/work/Hex-Action-Manifest/Hex-Action-Manifest/manifest.json
          asset_name: hex_action_manifest_v${{ github.run_number }}.json
          asset_content_type: text/json